trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    echo "Installing dependencies..."
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Running your app or script..."
    python your_script.py
  displayName: 'Run application'
